const quotes_yo_soy = [
  'una persona ambiciosa, dedicada y me preocupo por las personas que amo.',
  'determinada y alegre.',
  'una persona dinámica y amigable.',
  'una persona muy animada.',
  'una persona responsable, me gusta mucho jugar al fútbol',
  'una persona que sueña grande, veo en el futuro una gran oportunidad de ser quien quiero ser.',
  'una persona soñadora.',
  'una persona responsable y valiente,me encantan el fútbol y la música.',
  'una persona soñadora y decidida, busco mis sueños.',
  'una persona imperfecta que intenta mejorar cada vez más, soy muy afortunada y me gusta salir con los amigos, pasar el tiempo con mi familia y jugar al baloncesto.',
  'una persona solidaria y me gusta divertirme con mis amigos.',
  'una persona muy estudiosa, mis asignaturas favoritas son Matemáticas, Química, Física y Español.',
  'una persona muy vivaz, pero guardo muchas cosas para mí.',
  'una persona que es pura emoción, me encanta hablar, comunicarme con los demás y animar a los que están a mi lado me hace muy bien.',
  'una persona muy sentimental, decidida y empática.',
  'una persona muy alegre, reflexiva y me gusta jugar al tenis.',
  'una persona que es pura emoción, me encanta hablar, comunicarme con los demás y animar a los que están a mi lado me hace muy bien',
  'una persona muy alegre y positiva.',
  'una persona que pasa más tiempo en mundos inventados que en mundos reales, aunque siempre trato de estar rodeada de buenas personas que ayudan a los demás.',
];

const quotes_quiero_ser = [
  'ser feliz y tener éxito',
  'una persona fuerte',
  'feliz y estar rodeada de personas que me gusten.',
  'alguien mejor en todos los sentidos y, principalmente, feliz.',
  'arquitecta y trabajar en algo relacionado con eso.',
  'capaz de entusiasmar a las personas que están cerca de mí.',
  'exitoso y trabajar en algo que me guste.',
  'médica para poder cuidar a las personas pero de otra manera.',
  'determinado, ser respetado por todos y trabajar en la profesión de mis sueños.',
  'una doctora exitosa y ser más feliz todos los días.',
  'una persona que busque ayudar a más y más personas, por eso busco inspiración en las personas que me rodean.',
  'exitoso y poder viajar por todo el mundo.',
  'seguir siendo una persona muy feliz y agradecida por las cosas buenas de la vida.',
  'un profesional en el área de exactas.',
  'un profesional que ayude a muchas personas necesitadas.',
  'un profesional que disfrute de mi trabajo y quiero tener una familia.',
  'ser médica para poder cuidar a las personas y construir a mi familia, antes quiero viajar y visitar muchos países.',
  'y mantener todos los lazos que construí durante mi vida y convertirme en un buen profesional en el área que elija.',
  'economista y ser feliz en mi profesión.',
];

const quotes_images = [
  '0.jpg',
  '1.jpeg',
  '2.png',
  '4.jpg',
  '5.jpg',
  '6.jpeg',
  '7.jpeg',
  '8.jpeg',
  '9.png',
  '10.jpeg',
  '11.jpg',
  '12.png',
  '13.jpg',
  '14.png',
  '15.jpeg',
  '16.jpeg',
  '17.jpeg',
  '18.jpeg',
  '19.jpeg',
  '20.jpeg',
  '21.jpg',
];
